// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "SwiftShaders",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
        .tvOS(.v17),
        .visionOS(.v1),
    ],
    products: [
        .library(
            name: "SwiftShaders",
            targets: ["SwiftShaders"]
        ),
        // The gallery's catalogue, split out of the executable so that tests can
        // `import` it. A test target cannot import an executable target, which
        // is why the catalogue used to be checked by parsing its own source text
        // — a guard that could only ever be as good as the parser.
        .library(
            name: "SwiftShadersGalleryCore",
            targets: ["SwiftShadersGalleryCore"]
        ),
    ],
    targets: [
        // The `.metal` sources live in `Metal/` and are excluded from the Swift
        // build: SwiftPM's command-line build has no Metal rule. `Scripts/build-shaders.sh`
        // compiles them into `Resources/default.metallib`, which ships as a resource
        // and is reached at runtime via `ShaderLibrary.bundle(.module)`.
        //
        // Earlier this target declared the shader *directories* as `.process`
        // resources, which made SwiftPM treat the sibling `.swift` files as
        // resource data too and silently dropped most modifiers from the build.
        .target(
            name: "SwiftShaders",
            path: "Sources/SwiftShaders",
            exclude: ["Metal"],
            resources: [
                .copy("Resources/default.metallib"),
                // The signature manifest generated by
                // `Scripts/extract-metal-signatures.py` from the metallib. It is
                // the reviewable record of the Metal surface, and the only
                // description of shader parameter *types* available at runtime:
                // `MTLFunction` exposes no parameter list, so nothing else can
                // tell a call site how many arguments its function expects.
                .copy("Resources/shader-signatures.tsv"),
                // The stitchable functions no `ShaderBinding` declaration
                // reaches — generated from the metallib and the Swift sources
                // together, so the list cannot go stale unnoticed. Declared as a
                // resource because it lives in the target directory; nothing
                // reads it at runtime.
                .copy("Resources/unbound-functions.txt"),
            ]
        ),
        // Effect descriptions, the catalogue and the sample views the gallery
        // previews effects on. Importable, so the catalogue-consistency and
        // render-sweep tests exercise the real values rather than a text parse.
        .target(
            name: "SwiftShadersGalleryCore",
            dependencies: ["SwiftShaders"],
            path: "Sources/SwiftShadersGalleryCore"
        ),
        // The app shell — `@main`, the browsing UI, the pasteboard — lives in
        // its own package at `Gallery/`, which depends on this one by path. It
        // is the library's first external consumer, so building it proves the
        // package is usable from outside its own build graph. This manifest
        // vends libraries only.
        .testTarget(
            name: "SwiftShadersTests",
            dependencies: ["SwiftShaders", "SwiftShadersGalleryCore"]
        ),
    ]
)
