// SwiftShadersCommon.h
// Helpers shared by every .metal file in this package.
//
// WHY THIS FILE EXISTS
// --------------------
// Before this header, the same handful of primitives were re-typed file after
// file: the sine hash 12 times, perceptual luminance 6 times under two
// different names, and 2D value noise 8 times. Every copy was a place the
// package could silently disagree with itself, and several of them already
// did.
//
// HOW TO USE IT
// -------------
//   #include "SwiftShadersCommon.h"
// after the system includes. `Scripts/build-shaders.sh` compiles each .metal
// with `xcrun metal -c`, so the quoted include resolves relative to the
// including file — no include-path flag is needed. The script globs `*.metal`,
// so this header is never compiled on its own.
//
// RULES FOR ADDING TO THIS FILE
// -----------------------------
// 1. Helpers are `inline`, never `static`. A `static` helper that a given
//    translation unit does not happen to call produces a -Wunused-function
//    warning in that unit; an `inline` one does not. The shader build is free
//    of unused-function warnings and must stay that way.
// 2. Nothing here is `[[stitchable]]`. This header must never change the
//    metallib's exported surface — `Resources/shader-signatures.tsv` is the
//    contract, it is regenerated by every build, and it must stay
//    byte-identical unless a shader signature is deliberately changed.
// 3. When two shaders compute "the same thing" with different constants they
//    are NOT the same helper. Give each an honest name and document the
//    difference rather than unifying them and silently re-rendering an effect.
//    The sine-hash section below is the live example.

#ifndef SWIFTSHADERS_COMMON_H
#define SWIFTSHADERS_COMMON_H

#include <metal_stdlib>

// Every .metal file in this package already opens with `using namespace metal;`
// immediately after `#include <metal_stdlib>`, so hoisting it here changes no
// name lookup anywhere. It keeps the helper bodies below readable as ordinary
// MSL instead of `metal::`-qualified noise.
using namespace metal;

// MARK: - Colour

/// Rec. 601 perceptual luminance of a colour triple.
///
/// Replaces six byte-identical definitions that lived under two names:
/// `luminance` (Emboss, Neon, Sketch) and `getLuminance` (Invert, Sepia,
/// Threshold).
inline float luminance(half3 color) {
    return dot(float3(color), float3(0.299, 0.587, 0.114));
}

// MARK: - Sine hashes
//
// Four sine-hash variants are in use across the package. They are NOT
// interchangeable. `fract(sin(x) * K)` is chaotic in K, so changing the scale
// constant — even in the last three digits — re-randomises the whole field and
// visibly re-renders every effect built on it. The variants are therefore kept
// distinct, with names that state what differs:
//
//   hashSine1D               fract(sin(n)                          * 43758.5453123)
//   hashSine2D               fract(sin(dot(p, {127.1,   311.7}))   * 43758.5453)
//   hashSine2DExtended       fract(sin(dot(p, {127.1,   311.7}))   * 43758.5453123)
//   hashSine2DAlternateSeed  fract(sin(dot(p, {12.9898,  78.233})) * 43758.5453)
//
// "Extended" names the longer scale constant; "AlternateSeed" names the
// different dot-product seed. Do not collapse these into one helper: there is
// no correct winner, only a choice about which shaders get re-randomised.

/// Scalar sine hash. Was `hash` (Raymarching) and `glitchHash` (Glitch).
inline float hashSine1D(float n) {
    return fract(sin(n) * 43758.5453123);
}

/// 2D sine hash. Was `hash` (Frost, Mosaic, Particles, Sketch) and
/// `electricHash` (Electric) — five identical copies.
inline float hashSine2D(float2 p) {
    return fract(sin(dot(p, float2(127.1, 311.7))) * 43758.5453);
}

/// 2D sine hash with the extended scale constant. Was `noiseHash` (Noise),
/// `dissolveHash` (Dissolve) and `holoHash` (Hologram).
inline float hashSine2DExtended(float2 p) {
    return fract(sin(dot(p, float2(127.1, 311.7))) * 43758.5453123);
}

/// 2D sine hash seeded with the classic (12.9898, 78.233) pair. Was
/// `dispHash` (Displacement) and `voronoiHash1` (Voronoi).
inline float hashSine2DAlternateSeed(float2 p) {
    return fract(sin(dot(p, float2(12.9898, 78.233))) * 43758.5453);
}

/// 2D sine hash returning a 2D value. Was `hash2` (Mosaic, Particles).
inline float2 hashSine2DTo2D(float2 p) {
    return fract(sin(float2(dot(p, float2(127.1, 311.7)),
                            dot(p, float2(269.5, 183.3)))) * 43758.5453);
}

// MARK: - Value noise
//
// The eight copies of 2D value noise in this package were written in two
// different-looking interpolation forms:
//     mix(a, b, u.x) + (c - a) * u.y * (1 - u.x) + (d - b) * u.x * u.y
//     mix(mix(a, b, u.x), mix(c, d, u.x), u.y)
// Expanding both gives a + (b-a)u.x + (c-a)u.y + (a-b-c+d)u.x*u.y — they are
// the same bilinear interpolation. Measured maximum float32 divergence is
// 1.79e-07, four orders of magnitude below one 8-bit colour quantum, so the
// two forms are safely deduped into `bilerpLattice` below.
//
// What is NOT safe to dedupe is the hash underneath, which is why there are
// still three value-noise entry points instead of one.

/// Bilinear interpolation of the four corner samples of a noise lattice cell.
inline float bilerpLattice(float a, float b, float c, float d, float2 u) {
    return mix(mix(a, b, u.x), mix(c, d, u.x), u.y);
}

/// 2D value noise over `hashSine2D`. Was `noise2D` (Frost), `noise` (Sketch)
/// and `electricNoise` (Electric). Particles had a `noise` of its own, but it
/// was deleted as unreferenced rather than migrated here.
inline float valueNoise2D(float2 p) {
    float2 i = floor(p);
    float2 u = fract(p);
    u = u * u * (3.0 - 2.0 * u);

    return bilerpLattice(hashSine2D(i),
                         hashSine2D(i + float2(1.0, 0.0)),
                         hashSine2D(i + float2(0.0, 1.0)),
                         hashSine2D(i + float2(1.0, 1.0)),
                         u);
}

/// 2D value noise over `hashSine2DExtended`. Was `valueNoise` (Noise) and
/// `dissolveNoise` (Dissolve). Produces a different field from
/// `valueNoise2D` — see the sine-hash note above.
inline float valueNoise2DExtended(float2 p) {
    float2 i = floor(p);
    float2 u = fract(p);
    u = u * u * (3.0 - 2.0 * u);

    return bilerpLattice(hashSine2DExtended(i),
                         hashSine2DExtended(i + float2(1.0, 0.0)),
                         hashSine2DExtended(i + float2(0.0, 1.0)),
                         hashSine2DExtended(i + float2(1.0, 1.0)),
                         u);
}

/// 2D value noise that hashes a single scalar lattice index (i.x + i.y * 57)
/// rather than the 2D coordinate, so its field repeats wherever that index
/// collides. Genuinely a different algorithm, not a different constant.
/// Was `fireNoise` (Fire) and `waterNoise` (Water).
inline float valueNoiseLattice(float2 p) {
    float2 i = floor(p);
    float2 u = fract(p);
    u = u * u * (3.0 - 2.0 * u);

    float n = i.x + i.y * 57.0;
    return bilerpLattice(fract(sin(n) * 43758.5453),
                         fract(sin(n + 1.0) * 43758.5453),
                         fract(sin(n + 57.0) * 43758.5453),
                         fract(sin(n + 58.0) * 43758.5453),
                         u);
}

#endif // SWIFTSHADERS_COMMON_H
