import XCTest
import Metal
@testable import SwiftShaders

/// The build gate for the shader library itself.
///
/// `default.metallib` is generated by `Scripts/build-shaders.sh` and is not
/// committed. SwiftPM only *warns* about a declared-but-missing resource, so
/// without these tests `swift build` succeeds and ships a package in which every
/// effect fails at draw time. These are the tests that turn that into a red build.
final class ShaderLibraryIntegrityTests: XCTestCase {

    /// Lowest-level gate: the artifact is present in the resource bundle.
    /// Deliberately has no GPU dependency, so it fails loudly even on a runner
    /// with no Metal device.
    func testMetallibIsPresentInResourceBundle() throws {
        let url = Bundle.module.url(forResource: "default", withExtension: "metallib")
            ?? Bundle.module.url(forResource: "Resources/default", withExtension: "metallib")

        let found = try XCTUnwrap(
            url,
            """
            default.metallib is missing from the SwiftShaders resource bundle.
            Run `./Scripts/build-shaders.sh` (or `make build`) before `swift build`.
            SwiftPM does not compile .metal files and only warns when this resource
            is absent, so the package otherwise builds green with no shaders at all.
            """
        )

        let size = try FileManager.default
            .attributesOfItem(atPath: found.path)[.size] as? Int ?? 0
        XCTAssertGreaterThan(size, 1024, "default.metallib exists but is implausibly small (\(size) bytes)")
    }

    /// The library loads and holds the functions the Swift side binds against.
    func testMetallibLoadsAndExposesExpectedFunctions() throws {
        guard let device = MTLCreateSystemDefaultDevice() else {
            throw XCTSkip("No Metal device in this test process; bundle presence is covered separately.")
        }

        let library = try device.makeDefaultLibrary(bundle: .module)
        let names = Set(library.functionNames)

        // 256 stitchable functions at the time of writing. A floor rather than an
        // exact count so that removing genuinely dead shaders is not a test failure —
        // a partial or empty metallib still trips this immediately.
        XCTAssertGreaterThanOrEqual(
            names.count, 200,
            "Expected the metallib to expose ~256 stitchable functions, found \(names.count). "
            + "A short count usually means build-shaders.sh partially failed."
        )

        // Spot checks across all three effect kinds, so a truncated link is caught.
        for expected in ["invert", "wave", "sepia", "ripple", "crtLayerEffect"] {
            XCTAssertTrue(names.contains(expected), "metallib is missing '\(expected)'")
        }
    }
}
