import XCTest

/// The shaders nothing can reach.
///
/// 49 of the 256 stitchable functions in `default.metallib` have no
/// `ShaderBinding` declaration. They compile, they ship, and no Swift call site
/// names them. That is not a defect — most are variants somebody wrote and never
/// wired up — but it was invisible: the only way to learn the number was to
/// disassemble the metallib and diff it against a source scan by hand, which is
/// how it stayed at 49 for the whole remediation without anyone deciding it
/// should.
///
/// `Sources/SwiftShaders/Resources/unbound-functions.txt` is generated by
/// `Scripts/extract-metal-signatures.py` (called from `build-shaders.sh`) and
/// checked in. This test is its staleness guard, mirroring the manifest guard:
/// it recomputes the list from the two artifacts the script uses — the committed
/// manifest and the Swift sources — and fails if the committed file disagrees.
final class UnboundFunctionInventoryTests: XCTestCase {

    func testTheCommittedInventoryMatchesTheManifestAndTheSources() throws {
        let bound = Set(try ShaderBindingSourceScanner.scanDeclarations().map(\.functionName))
        let expected = try ShaderSignatureManifest.load()
            .keys
            .filter { !bound.contains($0) }
            .sorted()

        let committed = try Self.committedInventory()

        XCTAssertEqual(
            committed, expected,
            "Sources/SwiftShaders/Resources/unbound-functions.txt is stale. "
            + "Now unreachable but not listed: \(Set(expected).subtracting(committed).sorted()); "
            + "listed but now bound or gone: \(Set(committed).subtracting(expected).sorted()). "
            + "Run `bash Scripts/build-shaders.sh`."
        )
    }

    /// The header states the count. A header that disagrees with the body is the
    /// kind of thing a reader trusts and a generator forgets.
    func testTheHeaderCountMatchesTheBody() throws {
        let text = try Self.inventoryText()
        let stated = text
            .split(separator: "\n")
            .compactMap { line -> Int? in
                guard line.hasPrefix("# "), line.contains("unbound of") else { return nil }
                return Int(line.dropFirst(2).prefix { $0.isNumber })
            }
            .first

        XCTAssertEqual(stated, try Self.committedInventory().count)
    }

    /// Binding one of these is a *reduction*. If the number ever grows, someone
    /// has added a shader nothing calls — worth knowing at the time rather than
    /// at the next audit.
    ///
    /// **Lower this when you bind one.**
    static let unboundCeiling = 49

    func testTheUnboundCountOnlyEverFalls() throws {
        let count = try Self.committedInventory().count

        XCTAssertLessThanOrEqual(
            count, Self.unboundCeiling,
            "\(count) stitchable functions are unreachable, up from \(Self.unboundCeiling). "
            + "A new shader with no binding is a shader nobody can use."
        )
    }

    // MARK: - Reading the file

    private static func inventoryText() throws -> String {
        let url = ShaderCallSiteScanner.repositoryRoot
            .appendingPathComponent("Sources/SwiftShaders/Resources/unbound-functions.txt")
        return try String(contentsOf: url, encoding: .utf8)
    }

    private static func committedInventory() throws -> [String] {
        try inventoryText()
            .split(separator: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty && !$0.hasPrefix("#") }
    }
}
